language: java
jdk: openjdk11
dist: bionic

before_install:
  - chmod +x mvnw
  -
before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
    - env: JDK=11
      script: source ./install-jdk.sh --feature 11

after_script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}
  - ls ${JAVA_HOME}
  - java -version